extern const GeoLayout theplayerrolo_wcap_Wing_Cap_Switch_opt1[];
extern const GeoLayout theplayerrolo_wcap_Wing_Cap_Switch_opt2[];
extern const GeoLayout theplayerrolo_wcap_Wing_Cap_Switch_opt3[];
extern const GeoLayout theplayerrolo_wcap_geo[];
extern Lights1 theplayerrolo_wcap_SFOTHEggTop_lights;
extern Lights1 theplayerrolo_wcap_SFOTHEggMiddle_lights;
extern Lights1 theplayerrolo_wcap_Metal__METAL__lights;
extern u8 theplayerrolo_wcap_SFOTHEggTop_rgba16[];
extern u8 theplayerrolo_wcap_SFOTHEggMiddle_rgba16[];
extern u8 theplayerrolo_wcap_Metal_Shade_rgba16_rgba16[];
extern u8 theplayerrolo_wcap_Metal_Light_rgba16_rgba16[];
extern u8 theplayerrolo_wcap_wing_2_ia8[];
extern u8 theplayerrolo_wcap_wing1_ia8[];
extern Vtx theplayerrolo_wcap_Wing_Cap_mesh_layer_1_vtx_0[26];
extern Gfx theplayerrolo_wcap_Wing_Cap_mesh_layer_1_tri_0[];
extern Vtx theplayerrolo_wcap_Wing_Cap_mesh_layer_1_vtx_1[48];
extern Gfx theplayerrolo_wcap_Wing_Cap_mesh_layer_1_tri_1[];
extern Vtx theplayerrolo_wcap_Wings_mesh_layer_4_vtx_0[8];
extern Gfx theplayerrolo_wcap_Wings_mesh_layer_4_tri_0[];
extern Vtx theplayerrolo_wcap_Wings_mesh_layer_4_vtx_1[8];
extern Gfx theplayerrolo_wcap_Wings_mesh_layer_4_tri_1[];
extern Gfx mat_theplayerrolo_wcap_SFOTHEggTop[];
extern Gfx mat_revert_theplayerrolo_wcap_SFOTHEggTop[];
extern Gfx mat_theplayerrolo_wcap_SFOTHEggMiddle[];
extern Gfx mat_revert_theplayerrolo_wcap_SFOTHEggMiddle[];
extern Gfx mat_theplayerrolo_wcap_Metal__METAL_[];
extern Gfx mat_revert_theplayerrolo_wcap_Metal__METAL_[];
extern Gfx mat_theplayerrolo_wcap_Wing_Tip[];
extern Gfx mat_revert_theplayerrolo_wcap_Wing_Tip[];
extern Gfx mat_theplayerrolo_wcap_Wing_Base[];
extern Gfx mat_revert_theplayerrolo_wcap_Wing_Base[];
extern Gfx theplayerrolo_wcap_Wing_Cap_mesh_layer_1[];
extern Gfx theplayerrolo_wcap_Wing_Cap_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx theplayerrolo_wcap_Wings_mesh_layer_4[];
extern Gfx theplayerrolo_wcap_Wings_mesh_layer_4_mat_override_Metal__METAL__0[];
extern Gfx theplayerrolo_wcap_material_revert_render_settings[];
